language: php
php:
  - 7.1.9
services:
  - mysql
before install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS baseball;'  
  - mysql -u root --default-character-set=utf8 baseball < database/z_full_script.sql

